// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using patisserie_shop.EntityFrameworkCore;

#nullable disable

namespace patisserie_shop.Migrations
{
    [DbContext(typeof(patisserie_shopDbContext))]
    [Migration("20260630090000_MakeStockTransferSourceOptional")]
    partial class MakeStockTransferSourceOptional
    {
    }
}
