<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>patisserie_shop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\patisserie_shop.Application.Contracts\patisserie_shop.Application.Contracts.csproj" />
    <ProjectReference Include="../../modules/intelligence/src/Intelligence.HttpApi/Intelligence.HttpApi.csproj" />
    <ProjectReference Include="../../modules/operations/src/Operations.HttpApi/Operations.HttpApi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.PermissionManagement.HttpApi" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.FeatureManagement.HttpApi" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.SettingManagement.HttpApi" Version="10.1.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Identity.HttpApi" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.Account.HttpApi" Version="10.1.1" />
  </ItemGroup>
</Project>