<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>patisserie_shop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\patisserie_shop.Domain\patisserie_shop.Domain.csproj" />
    <ProjectReference Include="..\patisserie_shop.Application.Contracts\patisserie_shop.Application.Contracts.csproj" />
    <ProjectReference Include="../../modules/inventory/src/Inventory.Application/Inventory.Application.csproj" />
    <ProjectReference Include="../../modules/intelligence/src/Intelligence.Application/Intelligence.Application.csproj" />
    <ProjectReference Include="../../modules/production/src/Production.Application/Production.Application.csproj" />
    <ProjectReference Include="../../modules/operations/src/Operations.Application/Operations.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.Account.Application" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="10.1.1" />
  </ItemGroup>
</Project>